#!/bin/zsh

###############################################################################
# Demeter 1.0                                                                 #
#                                                                             # 
# Altair Bueno                                                                #
#                                                                             #
# This script provides a baseline for developing your own automator worklflow #
# with automatic uploads.                                                     #
#                                                                             # 
# 1. Create new Automator Workflow                                            #
# 2. Use calendar trigger                                                     #
# 3. Use 'Run Shell script'                                                   #
# 4. Write the path to this script. For example                               #
#    `$HOME/Demeter/scripts/demeter`                                          #
###############################################################################

export DEMETER="$HOME/Demeter"
export COMMIT_MESSAGE="[$(date '+%d/%m/%y')]: Scheduled job on $(uname -n)"

cd "$DEMETER"

# Has changes?
if [[ $(git diff --quiet > "$DEMETER/gitlog.txt") ]]
then 
	echo "No changes found"
else 
	# echo "true"
	echo "changes found, updating"
	if [[ $( { git fetch && git merge } >> "$DEMETER/gitlog.txt" ) ]]
	then
		echo "Found errors, check logs"
	else 
        git add --all
		git commit -am "$COMMIT_MESSAGE" >> "$DEMETER/gitlog.txt"
		git push  >> "$DEMETER/gitlog.txt"
		echo "Backup successful" 
	fi
fi