#!/bin/zsh

###############################################################################
# Demeter 1.0                                                                 #
# Altair Bueno MIT license                                                    #
# https://github.com/Altair-Bueno/Demeter                                     #
#                                                                             #
# This script provides a baseline for developing your own automator worklflow #
# with automatic uploads.                                                     #
#                                                                             # 
# 1. Create new Shortcuts Workflow                                            #
# 2. Use calendar trigger                                                     #
# 3. Use 'Run Shell script'                                                   #
# 4. Write the path to this script. For example                               #
#    `$HOME/Demeter/scripts/demeter`                                          #
###############################################################################

export DEMETER="$HOME/Demeter"
if [[ -z "$1" ]]
then 
	export COMMIT_MESSAGE="[$(date '+%d/%m/%y')]: Scheduled job on $(uname -n)"
else 
	export COMMIT_MESSAGE="$1"
fi

export LOG_FILE="$DEMETER/gitlog.txt"

cd "$DEMETER"

if [[ $(uname) == 'Darwin' ]]
then
	brew list | egrep "^[^(==>)]" | xargs > brew_packages.txt
elif [[ $(uname) == 'Linux' ]]
then
	echo not supported
fi

echo "$COMMIT_MESSAGE
********************************************************************************
" > "$LOG_FILE"

# Has changes?
if [[ $(git diff >> "$LOG_FILE") ]]
then 
	echo "No changes found"
else 
	# echo "true"
	echo "Found changes, updating"
	if [[ $( { git fetch && git merge } >> "$LOG_FILE" ) ]]
	then
		echo "Automatic merge failed. Check logs at $LOG_FILE"
	else 
  		git add --all >> "$LOG_FILE"
		git commit -am "$COMMIT_MESSAGE" >> "$LOG_FILE"
		git push  >> "$LOG_FILE"
		echo "Backup successful"
	fi
fi